name = "kuc-workers11pg"
main = "src/index.ts"
compatibility_date = "2023-09-04"
node_compat = true

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
# MY_VARIABLE = "production_value"

[vars]
API_KEY = "123"
DB_NAME = ""
DB_USERNAME = "postgres"
DB_HOST = ""
DB_PORT = "5432"
DB_PASSWORD = ""


